# Generated by Django 4.2.5 on 2023-09-06 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_car_color_alter_car_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='featured',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='engineType',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='api.enginetype'),
            preserve_default=False,
        ),
    ]
