# Generated by Django 4.2.5 on 2023-09-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_color_name_alter_condition_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
